README.md
Did not change any code, just did a perfunctory grammar revision on the readme.
=> Revised grammar in the readme.md

README.md
Update README.md to tell which terminal works on Windows
=> Update README.md to tell which terminal works on Windows

lib/index.js
=> add new square character to support more fonts

lib/index.js, package.json
Fixed the black square character. Now that's supposed to have a better support cross-operating systems. Fixed #14.
- Upgraded to [`git-stats-colors@2.1.0`](https://github.com/IonicaBizau/node-git-stats-colors) where the square character was fixed as well. Thanks @SanketDG! :cake:
- Upgraded to [`cli-box@5.0.0`](https://github.com/IonicaBizau/node-cli-box).
You can upgrade by running `npm i -g git-stats@latest`. :tada:
=> Dependencies and square characters

bin/git-stats, lib/index.js, package.json
In this pull request I'm adding the option to set a custom config file path when we init the `git-stats` package.
This fixes #8.
=> Code style, custom config file

bin/git-stats, lib/index.js
Some little fixes:
- moved the default values in the library
- use the `Package.homepage` as `docs_url`
=> Random fixes

.blah/README.ejs, MIGRATION.md, README.md, bin/git-stats, lib/index.js, package.json
Today, I have committed the final fixes in the new release documentation and fixed some minor bugs.
...and oh, yeah! I used my [Raspberry Pi](https://github.com/IonicaBizau/raspberry-pi) to write these docs. :smile: /cc @coltaemanuela
This completes the list from [this comment](https://github.com/IonicaBizau/git-stats/pull/47#issuecomment-132963972) and today evening, `git-stats 2.0.0` will be out! :sparkles: :tada:
=> Final documentation tweaks and improvements

.blah/README.ejs, README.md
:star2: :fireworks:  :star2: :fireworks:  :star2: :fireworks:  :star2: :fireworks:  :star2: 
Thanks for this nice feedback! My first repository which has 3k :star: I'm working on the new version of this tool.
If there is anything you can help with, contributions are always welcome! :smile: Please double check if there isn't already somebody working on the same issue (ask if not sure).
---
=> git-stats 2.0.0

LICENSE, README.md, package.json
- Added package.json
- Improved the documentation.
- Integrated **[json2md](https://github.com/IonicaBizau/json2md)** with **[blah](https://github.com/IonicaBizau/blah)** to get the best flexibility in generating documentation. :dizzy:
- Relicense to [MIT and link to the license](http://showalicense.com). :heart:
Regarding the integration of **json2md** into **blah**, [read this blog post I wrote](http://ionicabizau.net/blog/27-how-to-convert-json-to-markdown-using-json2md).
=> git-stats 2.9.0 Improved documentation

LICENSE, README.md, package.json
- Added badges :tada:
- [PayPal Donations](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=RVXDDLKKLQRJW)
- npm downloads
- npm version
- Travis (if there are tests)
- [CodeMentor](https://www.codementor.io/johnnyb?utm_source=github&utm_medium=button&utm_term=johnnyb&utm_campaign=github)–you can ping me there if you need help with one of these modules (or help in general).
- Updated the LICENSE year. :fireworks:
=> git-stats 2.9.2 Added badges

package.json
- Updated the README.md following the new template. :memo:
- Use [`babel-it`](https://github.com/IonicaBizau/babel-it) to babelify the code, so the module is now compatible with older versions of Node.js.
=> git-stats 2.9.6

lib/index.js, package.json
Fix variable which was not defined. Fixes #90.
=> git-stats 2.9.7

package.json
=> git-stats 2.9.9

README.md, package.json
- Updated the README.md following the new template. :memo:
- Add the [Patreon link](https://patreon.com/ionicabizau) in the README.md file. If you like what I'm doing, [supporting me](https://patreon.com/ionicabizau) would be awesome! Even **one dollar / month** would be helpful! Thanks! :heart:
=> git-stats 2.9.10

README.md, package.json
- Fix the [Patreon link](https://patreon.com/ionicabizau) in the README.md file. :memo:
=> git-stats 2.9.11

bin/git-stats, lib/index.js, package.json
Handle the since and until options in the `authors` output. /cc #79.
=> git-stats 2.9.13

package.json
Improve the raw results: include the raw theme object, levels and much more.
=> git-stats 2.9.14

README.md, bin/git-stats, package.json
This release is big! Fixed *all* the reported bugs and implemented custom exports:
- HTML (provided by [`git-stats-html`](https://github.com/IonicaBizau/git-stats-html). Fixed #63.
- Image exports by combining `git-stats-html` and `pageres` (see the documentation).  Fixed #50.
Hope you will enjoy it and share it with the world! :tada:
=> 2.10.0 :: Bug fixes, custom exports

bin/git-stats, package.json
Include `is-there` as module. Thanks @greut! :cake:
=> git-stats 2.10.1

DOCUMENTATION.md, LICENSE, README.md, bin/git-stats, package.json
Workaround to force 256 colors output
=> git-stats 2.10.2

lib/index.js, out.html, package.json
Fix the raw output for global activity. Fix #105.
=> git-stats 2.10.3

README.md
When I was following your walkthrough in your README.md I got an error, even though it is not hard to fix some people might get confused. So I added this for a simple disclaimer.
=> Added a slight clearer instruction

README.md, bin/git-stats, lib/index.js, package-lock.json
Hi, I want to add a new feature about filter the author.
For my case, I want to generate someone's commits only, so I added a flag `author`
do you have any advice?
Thanks!
=> feat: add author filter

LICENSE, README.md, lib/index.js, package-lock.json, package.json
Update dependencies, codebase restructure, npm audit fix
=> git-stats 3.0.0

package-lock.json, package.json
=> git-stats 3.1.1

README.md, lib/index.js, package.json
doc: first_day is depecated. close #121
=> doc: first_day is depecated. close #121

LICENSE, README.md, lib/index.js, package-lock.json, package.json
=> git-stats 3.1.2

.github/FUNDING.yml, CONTRIBUTING.md, package-lock.json, package.json
Add sponsor links:
- Patreon: https://patreon.com/ionizabizau
- Open Collective: https://opencollective.com/ionicabizau
- BuyMeACoffee: https://www.buymeacoffee.com/h96wwchmy
- GitHub Sponsors
=> git-stats 3.2.0

CONTRIBUTING.md, LICENSE, README.md, package-lock.json, package.json
 - Update the documentation.
>  - Add the GitHub Sponsors link. 
>
> As always, I am very grateful to those supporting my projects! You can do that by donating via [PayPal](http://paypal.me/IonicaBizau) or via GitHub Sponsors.
>
> Thank you very much! :heart:
>
=> git-stats 3.2.1
